POST http://localhost:8080/tutorials
content-type: application/json

{
    "title": "MongoDB",
    "description": "Wed, 21 Oct 2015 18:27:50 GMT",
    "published":1
}
###
GET http://localhost:8080/tutorials

###


GET http://localhost:8080/tutorials/1

###

POST http://localhost:8080/tutorials
content-type: application/json

{
    "title": "POSTRES SQL",
    "description": "Wed, 21 Oct 2015 18:27:50 GMT",
    "published":1
}
###

PUT http://localhost:8080/tutorials/1
content-type: application/json

{
    "title": "POSTRES SQL",
    "description": "Wed, 21 Oct 2015 18:27:50 GMT",
    "published":1
}
###
POST http://movieapp.dev:4000/account/login
content-type: application/json

{
        "username": "member_1",
        "password": "111"
}
###
GET http://localhost:6868/tutorials/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJxdWFuaHV5bmhAZ21haWwuY29tIiwiZ2FtZV9pZCI6MSwiaWF0IjoxNjM4NDE5NjY5LCJleHAiOjE2MzkwMjc2Njl9.G0Mn6FYPjXGScHzjCXu47Jx7-FUg9kRRgtpuyD2X4qg


